### ISSUE TITLE
background disappears when scrolling past viewport

### ISSUE THREAD

**Issue by ikanexus** [Tougrel/Pestoverse#17]
With `h-screen` being set on the flexbox wrappers for the site, the background colour only spreads until the end of the screen - when you scroll past that, you get a white background

Changing to `h-full` causes flexbox to not behave as expected - potentially need to apply the background on another element?

![image](https://github.com/Tougrel/Pestoverse/assets/137009494/8bffc78a-985b-45c3-a85a-55210ce7edca)

**Comment by Tougrel** [comment]
I will push an update on main to fix this cause i know why this is happening.

**Comment by Tougrel** [comment]
Check if b0d98cc fixed the issue and close this

**Comment by ikanexus** [comment]
yep that's looking good now 👍🏻
