### ISSUE TITLE
Map page

### ISSUE THREAD

**Issue by ikanexus** [Tougrel/Pestoverse#3]
Proposals:
1. Usage of leafletjs - visualise a flat map with pins for each location of the images

Questions:
1. On marker click - open up a slideshow of images at that location? Leaflet popup is too small and can only really handle one image

![image](https://github.com/Tougrel/Pestoverse/assets/137009494/cec245bc-daad-4b16-bcac-5a06fdde8c44)

- [x] Base Map
- [x] Full Screen Map
- [x] Smaller navigation buttons
- [x] Markers for each submission
- [x] Slideover to show images
- [x] Dark Mode
- [x] Modal / slideshow to expand images within slideover
- [x] use random bootfighter emotes as marker

**Comment by Tougrel** [comment]
I agree on using leaflet as the map library 👍 

Now for the popup... One way we could get around it is using the [Slideover](https://ui.nuxtlabs.com/overlays/slideover) component. When someone clicks the marker the slideover opens and we can put all images there.

**Comment by ikanexus** [comment]
Thinking about using nuxt-content and nuxt-content-assets to essentially be the 'database' for picture data (content as json/yaml files and images, rather than markdown) - I see you can programmatically retrieve the content data as well as being able to render to page straight away

**Comment by Tougrel** [comment]
I think the [MDC](https://content.nuxtjs.org/guide/writing/mdc) syntax will be better as we could use vue components to render stuff. We could also use them to

**Comment by Tougrel** [comment]
The first problem we could solve it by letting me host the images on my own API if we want but we will have to find a different way to upload images cause my API just serves them and doesn't optimize them or anything.

For the metadata I don't have any idea right now but I will check what we can do once I'm back!

**Comment by Tougrel** [comment]
We should also consider random emotes as map marks instead of having the standard leaf 👍
