### ISSUE TITLE
System theme icon not changing

### ISSUE THREAD

**Issue by Tougrel** [Tougrel/Pestoverse#9]
If you select the white or dark theme and refresh (or visit the page later) the "system" icon on the theme will stay there even if you switch to the system mode. This behavior appears in both [development](https://ace-reprint-vision-fans.trycloudflare.com/) and [production](https://pestoverse.tougrel.dev/)

**Comment by ikanexus** [comment]
Bizzarely I can't seem to replicate this on my deployment, but I can on yours https://map.pestoverse-ikanexus.pages.dev/

**Comment by Tougrel** [comment]
Yeah I can't seem to replicate this on your deployment 🤔 Maybe the changes you did on the navigation have already fixed a problem that I can't see 🤣

**Comment by Tougrel** [comment]
This was fixed in #4
